import {
  Code,
  Brain,
  Database,
  Shield,
  Smartphone,
  Cloud,
  Cog,
  Blocks,
  Code2,
  Cpu,
  Lightbulb,
  User,
  Heart,
  Plane,
  GraduationCap,
  Coffee,
  PiggyBank,
  TrendingUp,
  Gamepad2,
} from "lucide-react";

export const preferredArticleCategories = [
  { name: "Web Development", Icon: Code },
  { name: "Artificial Intelligence", Icon: Brain },
  { name: "Data Science", Icon: Database },
  { name: "Cybersecurity", Icon: Shield },
  { name: "Mobile App Development", Icon: Smartphone },
  { name: "Cloud Computing", Icon: Cloud },
  { name: "DevOps", Icon: Cog },
  { name: "Blockchain", Icon: Blocks },
  { name: "Programming Languages", Icon: Code2 },
  { name: "Machine Learning", Icon: Cpu },
  { name: "Entrepreneurship", Icon: Lightbulb },
  { name: "Personal Development", Icon: User },
  { name: "Health and Wellness", Icon: Heart },
  { name: "Travel", Icon: Plane },
  { name: "Education", Icon: GraduationCap },
  { name: "Lifestyle", Icon: Coffee },
  { name: "Finance and Investment", Icon: PiggyBank },
  { name: "Marketing Strategies", Icon: TrendingUp },
  { name: "Gaming and Entertainment", Icon: Gamepad2 },
];
